pipeline {
    agent {
        label "master"
    }
    options {
        timeout(time: 10, unit: 'MINUTES')
    }
    triggers {
        cron('H 0 * * *')
    }
    stages {
        stage('gradle build') {
            steps {
                sh '''
                   cd frontend-test
                   ./gradlew build
                   '''
            }
        }
        stage('sonar') {
            steps {
                sh '''
                   cd frontend-test
                   sonar-scanner \
                   -Dsonar.projectKey=frontend-test \
                   -Dsonar.sources=. \
                   -Dsonar.java.source=1.8 \
                   -Dsonar.java.binaries=build/classes \
                   -Dsonar.host.url=http://piotr-sonar.eu.ngrok.io/ \
                   -Dsonar.login=28e3478c5aab55128d7caf542d3d0a32646c1345
                   '''
            }
        }
    }
}
