package com.pfm.auth;

import io.swagger.annotations.ApiModelProperty;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
public final class AppUser {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @ApiModelProperty(value = "AppUser id (generated by application)", required = true, example = "1")
  private Long id;

  @ApiModelProperty(value = "AppUser name", required = true, example = "Marian")
  private String username;

  @ApiModelProperty(value = "AppUser password", required = true, example = "123456789Marian")
  private String password;

  @ApiModelProperty(value = "AppUser first name", required = true, example = "Marian")
  private String firstName;

  @ApiModelProperty(value = "AppUser last name", required = true, example = "Pazdzioch")
  private String lastName;

}
