CREATE TABLE ACCOUNT_TABLE
(
ID INT IDENTITY (1, 1) NOT NULL ,
CURRENCY NVARCHAR(3) NOT NULL ,
ACCOUNT_NUMBER NVARCHAR(20) NOT NULL ,
BALANCE DECIMAL(12,2) NOT NULL ,
LAST_MODIFIED_TS DATETIME NOT NULL ,
USER_ID INT NOT NULL,
);