package com.pfm.account;


import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class AccountValidator {

  public List<String> validate(Account account) {
    List<String> validationErrors = new ArrayList<>();

    if (account.getId() != null) {
      validationErrors.add("Account id must not be provided, it's generated by the application");
    }

    if (account.getName() == null) { // TODO - please check for empty strings like "", "  " etc.
      validationErrors.add("Account name cannot be empty");
    }

    if (account.getBalance() == null) {
      validationErrors.add("Account balance must be provided");
    }

    return validationErrors;
  }

}
