package com.pfm.account;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;

import java.util.ArrayList;
import java.util.List;

@Component
public class AccountValidator  {

    public List<String> validate(Account account) {
        List<String> validationResult = new ArrayList<>();
        if(account.getId()==null) {
            validationResult.add("Account id must not be provided, it's generated by the application");
        }
        if(account.getName()==null) {
            validationResult.add("Account name cannot be empty");
        }
        if(account.getBalance()==null) {
            validationResult.add("Account balance must be specified");
        }
return validationResult;
    }
}
