package com.pfm.history;

import io.swagger.annotations.ApiModelProperty;
import java.util.Map;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
@Entity
public class HistoryInfo {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @ApiModelProperty(value = "HistoryEntry id (generated by application)", required = true)
  private Long id;

  String name;

  String oldValue;

  String newValue;

}
