package com.pfm.history;

import io.swagger.v3.oas.annotations.media.Schema;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@Entity
@NoArgsConstructor
@AllArgsConstructor
public final class HistoryInfo {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Schema(description = "HistoryEntry id (generated by application)", required = true)
  private Long id;

  private String name;

  private String newValue;

  private String oldValue;

}
