package com.pfm.category;

import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class CategoryValidator {

  public List<String> validate(Category category) {
    List<String> validationResult = new ArrayList<>();

    if (category.getId() != null) {
      validationResult.add("Category id must not be provided, it's generated by the application");
    }

    if (category.getName() == null) { // TODO - please check for empty strings like "", "  " etc.
      validationResult.add("Category name cannot be empty");
    }

    return validationResult;
  }
}


