package com.pfm.category;

import com.pfm.account.Account;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class CategoryValidator {
    public List<String> validate(Category category) {
        List<String> validationResult = new ArrayList<>();
        if(category.getId()==null) {
            validationResult.add("Category id must not be provided, it's generated by the application");
        }
        if(category.getName()==null) {
            validationResult.add("Category name cannot be empty");
        }
        return validationResult;
    }
}


