# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: piokol/pfm:19

    timeout-minutes: 25

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: cd backend && chmod +x gradlew
    - run: ls -al
    - name: Build with Gradle
      run: cd backend && ./gradlew build -x generateGitProperties
    - name: Archive backend artifacts
      uses: actions/upload-artifact@v1
      with:
        name: backend
        path: backend/build/reports
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd frontend && sudo npm install
    - run: cd frontend && sudo npm install -g tslint typescript @angular/cli protractor protractor-retry
    - run: cd frontend && tslint --config tslint.json --project tsconfig.json
    - run: cd frontend && ng build
    - name: Update Chrome to latest version
      run: sudo apt-get -qqy update && sudo apt-get -qqy --assume-yes --no-install-recommends install google-chrome-stable
    - run: ./scripts/run_e2e.sh
